services:
  - type: web
    name: whatsapp-marketing
    env: node
    plan: free
    buildCommand: cd frontend && npm install --include=dev && npm run build && cd ../backend && npm install --include=dev
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        value: mongodb+srv://rsendix_admin:RSendixPro2026!@cluster0.exeq63f.mongodb.net/whatsapp_marketing?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_EMAIL
        value: admin@digitalsms.biz
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: CORS_ORIGIN
        value: https://whatsapp-marketing-c1qj.onrender.com
      - key: CLEANUP_ENABLED
        value: "false"
